name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - jupyterlab=4.0.8
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.3.1
  - ydata-profiling=4.5.1
  - pyarrow=13.0.0
  - wandb=0.15.12