name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - cookiecutter=2.4.0
  - gitpython=3.1.40
  - hydra-core=1.3.2
  - ipython=8.17.2
  - jupyterlab=4.0.8
  - matplotlib=3.8.1
  - mlflow=2.8.0
  - notebook=7.0.6
  - numpy=1.24.4
  - pandas=2.0.3
  - pip=23.3.1
  - python=3.11.6
  - wandb=0.15.12
