name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - pandas=2.0.3
  - pip=23.3.1
  - mlflow=2.8.0
  - scikit-learn=1.3.2
  - matplotlib=3.8.1
  - pillow=8.1.2
  - wandb=0.15.12